site_name: 52Pi Docs 
nav:
  - HOME: index.md
  - Conponents Introduction: 'md/conponent.md'
  - Projects for Arduino: 'md/arduino.md'
  - Projects for Raspbery Pi Pico Series: 'md/pico.md'
  - Projects for ESP32: 'md/esp32.md'
  - Projects for Raspberry Pi: 'md/rpi.md'
  - Contact: 'md/contact.md'

markdown_extensions:
   - pymdownx.hightlight:
       anchor_linenums: true
       line_spans: __span
       pygments_lang_class: true
   - pymdownx.inlinehilite
   - pymdownx.snippets
   - pymdownx.superfences
   - attr_list
   - md_in_html

plugins:
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
  
