site_name: 52Pi Docs 
nav:
  - HOME: 'md/index.md'
  - Components Introduction: 'md/component.md'
  - Education Starter Kit KZ-0073: 
    - What's in the kit: 'md/whatinkit.md'
    - Preparation: 'md/preparation.md'
    - Getting Start : 'md/gettingsa.md'
    - Project 1: 'md/arduino/p1.md'
    - Project 2: 'md/arduino/p2.md'
    - Project 3: 'md/arduino/p3.md'
    - Project 4: 'md/arduino/p4.md'
    - Project 5: 'md/arduino/p5.md'
    - Project 6: 'md/arduino/p6.md'
    - Project 7: 'md/arduino/p7.md'
    - Project 8: 'md/arduino/p8.md'
  - Contact: 
    - E-Mail: 'md/contact.md'

theme: readthedocs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

