site_name: 52Pi Docs 
nav:
  - HOME: 'index.md'
  - KZ-0069:
    - What's in the kit: 'md/kz-0069/whatisinthekit.md'
    - Getting Start: 'md/kz-0069/gettingstart.md'
    - Basic Usage 1: 'md/kz-0069/bu1.md'
    - Basic Usage 2: 'md/kz-0069/bu2.md'
    - Basic Usage 3: 'md/kz-0069/bu3.md'
    - Basic Usage 4: 'md/kz-0069/bu4.md'
    - Basic Usage 5: 'md/kz-0069/bu5.md'
    - Networking: 'md/kz-0069/networking.md'
    - MQTT broker: 'md/kz-0069/mqtt.md'
    - HomeAssistant: 'md/kz-0069/ha.md'

  - KZ-0068: 
    - What's in the kit: 'md/component.md'
    - Preparation: 'md/preparation.md'
    - Getting Start : 'md/gettingsa.md'
    - Project 1: 'md/kz-0068/arduino/p1.md'
    - Project 2: 'md/kz-0068/arduino/p2.md'
    - Project 3: 'md/kz-0068/arduino/p3.md'
    - Project 4: 'md/kz-0068/arduino/p4.md'
    - Project 5: 'md/kz-0068/arduino/p5.md'
    - Project 6: 'md/kz-0068/arduino/p6.md'
    - Project 7: 'md/kz-0068/arduino/p7.md'
    - Project 8: 'md/kz-0068/arduino/p8.md'
    - Project 9: 'md/kz-0068/arduino/p9.md'
    - Project 10: 'md/kz-0068/arduino/p10.md'

  - KZ-0073: 
    - What's in the kit: 'md/whatinkit.md'
    - Preparation: 'md/preparation.md'
    - Getting Start : 'md/gettingsa.md'
    - Project 1: 'md/arduino/p1.md'
    - Project 2: 'md/arduino/p2.md'
    - Project 3: 'md/arduino/p3.md'
    - Project 4: 'md/arduino/p4.md'
    - Project 5: 'md/arduino/p5.md'
    - Project 6: 'md/arduino/p6.md'
    - Project 7: 'md/arduino/p7.md'
    - Project 8: 'md/arduino/p8.md'
    - Project 9: 'md/arduino/p9.md'
    - Project 10: 'md/arduino/p10.md'
  - Contact: 
    - E-Mail: 'md/contact.md'

theme: readthedocs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

plugins:
  - mkdocs-video
